name: CI
on:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: volta-cli/action
        uses: volta-cli/action@v4.2.1

      # This line enables distribution
      # The "--stop-agents-after" is optional, but allows idle agents to shut down once the "e2e-ci" targets have been requested
      # - run: npx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"
      - run: yarn install --frozen-lockfile

      - uses: nrwl/nx-set-shas@v4

      - run: yarn dlx nx-cloud record -- nx format:check
      - run: yarn exec nx affected -t lint test build e2e-ci
